name: uk-salary-calculator # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.9.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Calculate take home pay based on your annual salary. # 79 char long summary
description: |
 Use this simple tool to see a breakdown of your take-home pay after tax and National Insurance contributions.
 Based on the UK tax year 2022-2023.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
architectures:
  - build-on: [ amd64 ]

parts:
  uk-salary-calculator:
    plugin: flutter
    source: https://github.com/local-optimum/uk_salary_calculator.git
    flutter-target: lib/main.dart

apps:
  uk-salary-calculator:
    command: uk-salary-calculator
    extensions: [flutter-master]
    plugs:
      [network]
